-- Drop RPC functions to keep supabase autogenerated types clean of malformed arguments
DROP FUNCTION IF EXISTS public.atualizar_email_usuario(UUID, TEXT);
DROP FUNCTION IF EXISTS public.proximo_numero_os(UUID);
